In [115]:
import numpy as np
import pandas as pd


# Scarichiamo e leggiamo i dati del train
dataset_file = 'dati/train.csv'
df = pd.read_csv(dataset_file)

# Sostituiamo le stringhe vuote ("") con NaN
df['sii'] = df['sii'].str.strip()
df['sii'] = df['sii'].replace("", np.nan)


# Eliminiamuo le righe con valori NaN (vuoti) nella colonna 'sii'
df_clean = df.dropna(subset=['sii'])
df_clean.head(10)

,id,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,...,PCIAT-PCIAT_18,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii
0,00008ff9,Fall,5,0,Winter,51,Fall,16.87731569,46.0,50.8,...,4,2,4,55,,,,Fall,3,2
1,000fd460,Summer,9,0,,,Fall,14.03559028,48.0,46.0,...,0,0,0,0,Fall,46,64,Summer,0,0
2,00105258,Summer,10,1,Fall,71,Fall,16.64869606,56.5,75.6,...,2,1,1,28,Fall,38,54,Summer,2,0
3,00115b9f,Winter,9,0,Fall,71,Summer,18.29234694,56.0,81.6,...,3,4,1,44,Summer,31,45,Winter,0,1
5,001f3379,Spring,13,1,Winter,50,Summer,22.27995198,59.5,112.2,...,1,2,1,34,Summer,40,56,Spring,0,1
6,0038ba98,Fall,10,0,,,Fall,19.66076033,55.0,84.6,...,4,1,0,20,Winter,27,40,Fall,3,0
11,00abe655,Fall,11,0,Summer,66,,,,,...,0,1,0,10,Winter,42,59,Fall,0,0
12,00ae59c9,Fall,13,0,,,Winter,21.07906523,57.75,100.0,...,2,2,1,31,Fall,33,47,Fall,1,1
15,00c0cd71,Winter,7,0,Summer,51,Spring,29.31577503,54.0,121.6,...,3,3,1,58,Spring,35,50,Winter,2,2
16,00d56d4b,Spring,5,1,Summer,80,Spring,17.28450413,44.0,47.6,...,0,0,0,0,Spring,37,53,Spring,0,0

In [116]:
# I valori mancanti sono solo spazi, li sostituiamo con NaN
df_clean = df_clean.replace(r'^\s*$', np.nan, regex=True)

nan_counts = df_clean.loc[:,['Basic_Demos-Age ', 'Basic_Demos-Sex ', 'PreInt_EduHx-computerinternet_hoursday ', 
                    'Physical-BMI ', 'Physical-Height ', 'Physical-Weight ', 'Physical-Waist_Circumference ', 
                    'SDS-SDS_Total_Raw ', 'CGAS-CGAS_Score ']].isna().sum()

nan_counts.head(10)

Basic_Demos-Age                               0
Basic_Demos-Sex                               0
PreInt_EduHx-computerinternet_hoursday       82
Physical-BMI                                209
Physical-Height                             206
Physical-Weight                             164
Physical-Waist_Circumference               2253
SDS-SDS_Total_Raw                           209
CGAS-CGAS_Score                             394
dtype: int64

In [117]:
data = df_clean[['Basic_Demos-Age ', 'Basic_Demos-Sex ', 'PreInt_EduHx-computerinternet_hoursday ', 
                    'Physical-BMI ', 'Physical-Height ', 'Physical-Weight ', 'Physical-Waist_Circumference ', 
                    'SDS-SDS_Total_Raw ', 'CGAS-CGAS_Score ']]

data = data.astype(float)
data.head(10)

,Basic_Demos-Age,Basic_Demos-Sex,PreInt_EduHx-computerinternet_hoursday,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,SDS-SDS_Total_Raw,CGAS-CGAS_Score
0,5.0,0.0,3.0,16.877316,46.00,50.8,NaN,NaN,51.0
1,9.0,0.0,0.0,14.035590,48.00,46.0,22.0,46.0,NaN
2,10.0,1.0,2.0,16.648696,56.50,75.6,NaN,38.0,71.0
3,9.0,0.0,0.0,18.292347,56.00,81.6,NaN,31.0,71.0
5,13.0,1.0,0.0,22.279952,59.50,112.2,NaN,40.0,50.0
6,10.0,0.0,3.0,19.660760,55.00,84.6,NaN,27.0,NaN
11,11.0,0.0,0.0,NaN,NaN,NaN,NaN,42.0,66.0
12,13.0,0.0,1.0,21.079065,57.75,100.0,NaN,33.0,NaN
15,7.0,0.0,2.0,29.315775,54.00,121.6,NaN,35.0,51.0
16,5.0,1.0,0.0,17.284504,44.00,47.6,NaN,37.0,80.0

In [119]:
# Sostituiamo i valori mancanti nel seguente modo:
# PreInt_EduHx-computerinternet_hoursday: media
# Physical-BMI: media
# Physical-Height: media
# Physical-Weight: media 
# Physical-Waist_Circumference: media
# SDS-SDS_Total_Raw: media
# CGAS-CGAS_Score: media

columns_to_fill = ['Basic_Demos-Age ', 'Basic_Demos-Sex ', 'PreInt_EduHx-computerinternet_hoursday ', 
                   'Physical-BMI ', 'Physical-Height ', 'Physical-Weight ', 'Physical-Waist_Circumference ', 
                   'SDS-SDS_Total_Raw ', 'CGAS-CGAS_Score ']

# Ciclo su ciascuna colonna e applico fillna con la media
for col in columns_to_fill:
    data[col].fillna(data[col].mean(), inplace=True)

data.head(10)

/var/folders/zq/gk5f556s7zq33crv9lknkrhm0000gn/T/ipykernel_29488/1541271766.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].mean(), inplace=True)

,Basic_Demos-Age,Basic_Demos-Sex,PreInt_EduHx-computerinternet_hoursday,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,SDS-SDS_Total_Raw,CGAS-CGAS_Score
0,5.0,0.0,3.0,16.877316,46.000000,50.800000,26.625259,40.977839,51.000000
1,9.0,0.0,0.0,14.035590,48.000000,46.000000,22.000000,46.000000,65.159266
2,10.0,1.0,2.0,16.648696,56.500000,75.600000,26.625259,38.000000,71.000000
3,9.0,0.0,0.0,18.292347,56.000000,81.600000,26.625259,31.000000,71.000000
5,13.0,1.0,0.0,22.279952,59.500000,112.200000,26.625259,40.000000,50.000000
6,10.0,0.0,3.0,19.660760,55.000000,84.600000,26.625259,27.000000,65.159266
11,11.0,0.0,0.0,19.125667,55.897051,87.839592,26.625259,42.000000,66.000000
12,13.0,0.0,1.0,21.079065,57.750000,100.000000,26.625259,33.000000,65.159266
15,7.0,0.0,2.0,29.315775,54.000000,121.600000,26.625259,35.000000,51.000000
16,5.0,1.0,0.0,17.284504,44.000000,47.600000,26.625259,37.000000,80.000000

In [120]:
# Age: età
# Sex: sesso
# Computer internet hours day: uso di internet al giorno
# BMI
# Altezza
# Peso
# Circonferenza vita
# SDS-SDS_Total_Raw: scala per capire i problemi legati al sonno per i ragazzi
# CGAS-CGAS_Score: punteggio dato dai clinici di ospedali mentali per capire la sanità mentale del paziente (
#                  valori alti -> buon funzionamento del cervello del paziente, valori bassi -> maggiori difficoltà)


X = data

print("X shape", X.shape)

y = df_clean.loc[:, 'sii']
print("y shape", y.shape)

X shape (2736, 9)
y shape (2736,)

In [121]:
from sklearn.model_selection import train_test_split

X_train80, X_test20, y_train80, y_test20 = train_test_split(X, y, test_size=0.20, random_state=42)
# display(X_train80, X_test20, y_train80, y_test20)

In [122]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

model = DecisionTreeClassifier(max_leaf_nodes=50)
model.fit(X_train80,y_train80)

# compute Accuracy
train_acc = accuracy_score(y_true = y_train80, y_pred = model.predict(X_train80))
test_acc  = accuracy_score(y_true = y_test20,  y_pred = model.predict(X_test20))
print ("Train Accuracy: {:.3f} - Test Accuracy: {:.3f}".format(train_acc,test_acc) )

# from sklearn.tree import plot_tree
# import matplotlib.pyplot as plt

# f_names = ['Age', 'Sex', 'Hours-Day']

# c_names = ["Very low","Low","Medium","High"]

# fig, ax = plt.subplots(figsize=(50, 50))
# plot_tree(model, ax=ax,
#          feature_names=f_names, class_names=c_names,
#                                 filled=True, rounded=True)

# plt.show()

Train Accuracy: 0.675 - Test Accuracy: 0.591

In [123]:
best_leaves = None
best_test_acc = 0

for max_leaves in range(2,50):
    # train and predict
    model2 = DecisionTreeClassifier(max_leaf_nodes=max_leaves)
    model2.fit(X_train80,y_train80)

    # compute Accuracy
    train_acc = accuracy_score(y_true = y_train80, y_pred = model2.predict(X_train80))
    test_acc  = accuracy_score(y_true = y_test20,  y_pred = model2.predict(X_test20))
    # Salva il valore migliore
    if test_acc > best_test_acc:
        best_test_acc = test_acc
        best_leaves = max_leaves

print(f"Il miglior numero di foglie è {best_leaves} con un'accuracy di {best_test_acc:.3f}")

Il miglior numero di foglie è 6 con un'accuracy di 0.637