In [6]:
import numpy as np
import pandas as pd


# Scarichiamo e leggiamo i dati del train
dataset_file = 'dati/train.csv'
df = pd.read_csv(dataset_file)

# Sostituiamo le stringhe vuote ("") con NaN
df['sii'] = df['sii'].str.strip()
df['PreInt_EduHx-computerinternet_hoursday '] = df['PreInt_EduHx-computerinternet_hoursday '].str.strip()

df['sii'] = df['sii'].replace("", np.nan)
df['PreInt_EduHx-computerinternet_hoursday '] = df['PreInt_EduHx-computerinternet_hoursday '].replace("",np.nan)


# Eliminiamuo le righe con valori NaN (vuoti) nella colonna 'sii'
df_clean = df.dropna(subset=['sii', 'PreInt_EdHx-computerinternet_hoursday '])
df_clean.head(10)

KeyError: ['PreInt_EdHx-computerinternet_hoursday ']

In [ ]:
X = df_clean.loc[:,['Basic_Demos-Age ', 'Basic_Demos-Sex ', 'PreInt_EduHx-computerinternet_hoursday ']] # intervallo da id fino alla penultima colonna
X = X.replace(r'^\s*$', np.nan, regex=True)
X = X.astype(float)

print("X shape", X.shape)

y = df_clean.loc[:, 'sii']
print("y shape", y.shape)

X shape (2654, 3)
y shape (2654,)

:

:

:

:

:

In [ ]:
X_train80, X_test20, y_train80, y_test20 = train_test_split(X, y, test_size=0.20, random_state=42)
display(X_train80, X_test20, y_train80, y_test20)

,Basic_Demos-Age,Basic_Demos-Sex,PreInt_EduHx-computerinternet_hoursday
3121,6.0,0.0,2.0
1318,6.0,0.0,0.0
3363,9.0,1.0,0.0
1667,9.0,0.0,2.0
2691,18.0,1.0,3.0
...,...,...,...
2451,8.0,0.0,1.0
1620,11.0,1.0,0.0
1663,9.0,0.0,0.0
1910,11.0,0.0,2.0
1272,6.0,0.0,0.0

,Basic_Demos-Age,Basic_Demos-Sex,PreInt_EduHx-computerinternet_hoursday
1225,6.0,0.0,2.0
181,6.0,0.0,0.0
2112,16.0,0.0,2.0
2405,7.0,0.0,0.0
1040,12.0,0.0,3.0
...,...,...,...
103,5.0,1.0,0.0
2014,14.0,1.0,3.0
2478,17.0,0.0,0.0
1267,9.0,1.0,1.0
1685,14.0,1.0,0.0

3121    0
1318    0
3363    0
1667    2
2691    3
       ..
2451    0
1620    1
1663    0
1910    1
1272    0
Name: sii, Length: 2123, dtype: object

1225    1
181     0
2112    0
2405    0
1040    1
       ..
103     0
2014    0
2478    2
1267    1
1685    1
Name: sii, Length: 531, dtype: object

:

:

:

:

:

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_leaf_nodes=20)
model.fit(X_train80,y_train80)

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

f_names = ['Age', 'Sex', 'Hours-Day']

c_names = ["merda","Low","Medium","High"]

fig, ax = plt.subplots(figsize=(50, 50))
plot_tree(model, ax=ax,
         feature_names=f_names, class_names=c_names,
                                filled=True, rounded=True)

NameError: name 'X_train80' is not defined

:

:

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.inspection import DecisionBoundaryDisplay

X_train = pd.DataFrame(X, columns=['Basic_Demos-Age ', 'Basic_Demos-Sex ', 'Physical-BMI ', 'PreInt_EduHx-computerinternet_hoursday '])
X_test = pd.DataFrame(X, columns=['Basic_Demos-Age ', 'Basic_Demos-Sex ', 'Physical-BMI ', 'PreInt_EduHx-computerinternet_hoursday '])

display(y)
display(y_train)



# train and predict
dt = DecisionTreeClassifier(max_leaf_nodes=2) # change this!
dt.fit(X_train,y_train)

# compute Accuracy
train_acc = accuracy_score(y_true = y_train, y_pred = dt.predict(X_train))
print ("Train Accuracy: {:.3f}".format(train_acc) )

#model_decision_boundary(dt, X_test, y_test)

fig, ax = plt.subplots(figsize=(4,4))
disp = DecisionBoundaryDisplay.from_estimator(
    dt, X_train[:, ['Basic_Demos-Age ', 'Basic_Demos-Sex ']],
    grid_resolution = 30, plot_method='pcolormesh',
    alpha=0.3, ax = ax)

ax.scatter(X_test[:,'Basic_Demos-Age '], X_test[:,'Basic_Demos-Sex '], c=y_test, edgecolor="k", alpha=0.5);

0       2
1       0
2       0
3       1
5       1
       ..
3953    0
3954    1
3955    1
3957    1
3958    0
Name: sii, Length: 2654, dtype: object

945     0
3245    0
3050    1
1634    0
2785    0
       ..
2451    0
1620    1
1663    0
1910    1
1272    0
Name: sii, Length: 1778, dtype: object

ValueError: Number of labels=1778 does not match number of samples=2654

:

:

:

:

:

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Max leaves

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

for max_leaves in range(2,500):
    # train and predict
    dt = DecisionTreeClassifier(max_leaf_nodes=max_leaves)
    dt.fit(X_train,y_train)

    # compute Accuracy
    train_acc = accuracy_score(y_true = y_train, y_pred = dt.predict(X_train))
    print ("Train Accuracy: {:.3f}".format(train_acc) )

Train Accuracy: 0.582
Train Accuracy: 0.593
Train Accuracy: 0.593
Train Accuracy: 0.594
Train Accuracy: 0.594
Train Accuracy: 0.594
Train Accuracy: 0.598
Train Accuracy: 0.598
Train Accuracy: 0.598
Train Accuracy: 0.602
Train Accuracy: 0.605
Train Accuracy: 0.610
Train Accuracy: 0.610
Train Accuracy: 0.611
Train Accuracy: 0.613
Train Accuracy: 0.614
Train Accuracy: 0.614
Train Accuracy: 0.615
Train Accuracy: 0.617
Train Accuracy: 0.617
Train Accuracy: 0.617
Train Accuracy: 0.617
Train Accuracy: 0.617
Train Accuracy: 0.621
Train Accuracy: 0.623
Train Accuracy: 0.623
Train Accuracy: 0.625
Train Accuracy: 0.626
Train Accuracy: 0.627
Train Accuracy: 0.628
Train Accuracy: 0.629
Train Accuracy: 0.629
Train Accuracy: 0.629
Train Accuracy: 0.629
Train Accuracy: 0.628
Train Accuracy: 0.629
Train Accuracy: 0.631
Train Accuracy: 0.631
Train Accuracy: 0.631
Train Accuracy: 0.632
Train Accuracy: 0.634
Train Accuracy: 0.637
Train Accuracy: 0.638
Train Accuracy: 0.638
Train Accuracy: 0.638
Train Accuracy: 0.640
Train Accuracy: 0.642
Train Accuracy: 0.642
Train Accuracy: 0.641
Train Accuracy: 0.645
Train Accuracy: 0.646
Train Accuracy: 0.646
Train Accuracy: 0.646
Train Accuracy: 0.649
Train Accuracy: 0.649
Train Accuracy: 0.651
Train Accuracy: 0.652
Train Accuracy: 0.652
Train Accuracy: 0.653
Train Accuracy: 0.653
Train Accuracy: 0.654
Train Accuracy: 0.654
Train Accuracy: 0.655
Train Accuracy: 0.656
Train Accuracy: 0.656
Train Accuracy: 0.657
Train Accuracy: 0.655
Train Accuracy: 0.658
Train Accuracy: 0.659
Train Accuracy: 0.659
Train Accuracy: 0.657
Train Accuracy: 0.660
Train Accuracy: 0.659
Train Accuracy: 0.661
Train Accuracy: 0.662
Train Accuracy: 0.662
Train Accuracy: 0.664
Train Accuracy: 0.663
Train Accuracy: 0.663
Train Accuracy: 0.665
Train Accuracy: 0.666
Train Accuracy: 0.669
Train Accuracy: 0.668
Train Accuracy: 0.670
Train Accuracy: 0.671
Train Accuracy: 0.671
Train Accuracy: 0.677
Train Accuracy: 0.673
Train Accuracy: 0.673
Train Accuracy: 0.678
Train Accuracy: 0.672
Train Accuracy: 0.683
Train Accuracy: 0.684
Train Accuracy: 0.686
Train Accuracy: 0.684
Train Accuracy: 0.686
Train Accuracy: 0.688
Train Accuracy: 0.689
Train Accuracy: 0.690
Train Accuracy: 0.691
Train Accuracy: 0.690
Train Accuracy: 0.691
Train Accuracy: 0.693
Train Accuracy: 0.694
Train Accuracy: 0.694
Train Accuracy: 0.695
Train Accuracy: 0.696
Train Accuracy: 0.695
Train Accuracy: 0.696
Train Accuracy: 0.700
Train Accuracy: 0.701
Train Accuracy: 0.701
Train Accuracy: 0.703
Train Accuracy: 0.704
Train Accuracy: 0.704
Train Accuracy: 0.705
Train Accuracy: 0.705
Train Accuracy: 0.706
Train Accuracy: 0.705
Train Accuracy: 0.706
Train Accuracy: 0.708
Train Accuracy: 0.710
Train Accuracy: 0.709
Train Accuracy: 0.709
Train Accuracy: 0.714
Train Accuracy: 0.714
Train Accuracy: 0.711
Train Accuracy: 0.715
Train Accuracy: 0.717
Train Accuracy: 0.719
Train Accuracy: 0.720
Train Accuracy: 0.720
Train Accuracy: 0.722
Train Accuracy: 0.723
Train Accuracy: 0.724
Train Accuracy: 0.725
Train Accuracy: 0.723
Train Accuracy: 0.723
Train Accuracy: 0.727
Train Accuracy: 0.727
Train Accuracy: 0.729
Train Accuracy: 0.728
Train Accuracy: 0.730
Train Accuracy: 0.729
Train Accuracy: 0.731
Train Accuracy: 0.731
Train Accuracy: 0.731
Train Accuracy: 0.733
Train Accuracy: 0.731
Train Accuracy: 0.733
Train Accuracy: 0.735
Train Accuracy: 0.734
Train Accuracy: 0.736
Train Accuracy: 0.737
Train Accuracy: 0.737
Train Accuracy: 0.738
Train Accuracy: 0.737
Train Accuracy: 0.740
Train Accuracy: 0.740
Train Accuracy: 0.740
Train Accuracy: 0.741
Train Accuracy: 0.742
Train Accuracy: 0.742
Train Accuracy: 0.742
Train Accuracy: 0.743
Train Accuracy: 0.744
Train Accuracy: 0.744
Train Accuracy: 0.745
Train Accuracy: 0.746
Train Accuracy: 0.746
Train Accuracy: 0.743
Train Accuracy: 0.746
Train Accuracy: 0.743
Train Accuracy: 0.744
Train Accuracy: 0.747
Train Accuracy: 0.747
Train Accuracy: 0.747
Train Accuracy: 0.749
Train Accuracy: 0.749
Train Accuracy: 0.749
Train Accuracy: 0.749
Train Accuracy: 0.749
Train Accuracy: 0.751
Train Accuracy: 0.750
Train Accuracy: 0.750
Train Accuracy: 0.751
Train Accuracy: 0.752
Train Accuracy: 0.752
Train Accuracy: 0.754
Train Accuracy: 0.754
Train Accuracy: 0.754
Train Accuracy: 0.755
Train Accuracy: 0.755
Train Accuracy: 0.756
Train Accuracy: 0.758
Train Accuracy: 0.756
Train Accuracy: 0.759
Train Accuracy: 0.759
Train Accuracy: 0.760
Train Accuracy: 0.760
Train Accuracy: 0.749
Train Accuracy: 0.762
Train Accuracy: 0.761
Train Accuracy: 0.761
Train Accuracy: 0.762
Train Accuracy: 0.763
Train Accuracy: 0.763
Train Accuracy: 0.764
Train Accuracy: 0.764
Train Accuracy: 0.765
Train Accuracy: 0.766
Train Accuracy: 0.765
Train Accuracy: 0.766
Train Accuracy: 0.767
Train Accuracy: 0.767
Train Accuracy: 0.767
Train Accuracy: 0.768
Train Accuracy: 0.769
Train Accuracy: 0.768
Train Accuracy: 0.769
Train Accuracy: 0.771
Train Accuracy: 0.772
Train Accuracy: 0.772
Train Accuracy: 0.772
Train Accuracy: 0.769
Train Accuracy: 0.773
Train Accuracy: 0.774
Train Accuracy: 0.774
Train Accuracy: 0.775
Train Accuracy: 0.775
Train Accuracy: 0.774
Train Accuracy: 0.777
Train Accuracy: 0.777
Train Accuracy: 0.779
Train Accuracy: 0.777
Train Accuracy: 0.776
Train Accuracy: 0.778
Train Accuracy: 0.781
Train Accuracy: 0.780
Train Accuracy: 0.780
Train Accuracy: 0.782
Train Accuracy: 0.781
Train Accuracy: 0.783
Train Accuracy: 0.782
Train Accuracy: 0.783
Train Accuracy: 0.785
Train Accuracy: 0.785
Train Accuracy: 0.786
Train Accuracy: 0.787
Train Accuracy: 0.787
Train Accuracy: 0.787
Train Accuracy: 0.787
Train Accuracy: 0.787
Train Accuracy: 0.787
Train Accuracy: 0.789
Train Accuracy: 0.789
Train Accuracy: 0.790
Train Accuracy: 0.791
Train Accuracy: 0.790
Train Accuracy: 0.792
Train Accuracy: 0.792
Train Accuracy: 0.793
Train Accuracy: 0.794
Train Accuracy: 0.791
Train Accuracy: 0.791
Train Accuracy: 0.794
Train Accuracy: 0.795
Train Accuracy: 0.794
Train Accuracy: 0.796
Train Accuracy: 0.797
Train Accuracy: 0.796
Train Accuracy: 0.797
Train Accuracy: 0.798
Train Accuracy: 0.794
Train Accuracy: 0.800
Train Accuracy: 0.798
Train Accuracy: 0.799
Train Accuracy: 0.800
Train Accuracy: 0.801
Train Accuracy: 0.800
Train Accuracy: 0.803
Train Accuracy: 0.803
Train Accuracy: 0.804
Train Accuracy: 0.803
Train Accuracy: 0.805
Train Accuracy: 0.803
Train Accuracy: 0.803
Train Accuracy: 0.807
Train Accuracy: 0.803
Train Accuracy: 0.805
Train Accuracy: 0.808
Train Accuracy: 0.807
Train Accuracy: 0.808
Train Accuracy: 0.806
Train Accuracy: 0.810
Train Accuracy: 0.808
Train Accuracy: 0.810
Train Accuracy: 0.808
Train Accuracy: 0.811
Train Accuracy: 0.809
Train Accuracy: 0.813
Train Accuracy: 0.811
Train Accuracy: 0.813
Train Accuracy: 0.813
Train Accuracy: 0.812
Train Accuracy: 0.812
Train Accuracy: 0.812
Train Accuracy: 0.811
Train Accuracy: 0.813
Train Accuracy: 0.816
Train Accuracy: 0.812
Train Accuracy: 0.815
Train Accuracy: 0.815
Train Accuracy: 0.818
Train Accuracy: 0.816
Train Accuracy: 0.817
Train Accuracy: 0.817
Train Accuracy: 0.817
Train Accuracy: 0.818
Train Accuracy: 0.819
Train Accuracy: 0.819
Train Accuracy: 0.819
Train Accuracy: 0.820
Train Accuracy: 0.816
Train Accuracy: 0.823
Train Accuracy: 0.821
Train Accuracy: 0.820
Train Accuracy: 0.824
Train Accuracy: 0.823
Train Accuracy: 0.821
Train Accuracy: 0.818
Train Accuracy: 0.822
Train Accuracy: 0.823
Train Accuracy: 0.824
Train Accuracy: 0.822
Train Accuracy: 0.824
Train Accuracy: 0.825
Train Accuracy: 0.825
Train Accuracy: 0.825
Train Accuracy: 0.824
Train Accuracy: 0.823
Train Accuracy: 0.826
Train Accuracy: 0.828
Train Accuracy: 0.827
Train Accuracy: 0.827
Train Accuracy: 0.828
Train Accuracy: 0.829
Train Accuracy: 0.831
Train Accuracy: 0.830
Train Accuracy: 0.831
Train Accuracy: 0.831
Train Accuracy: 0.831
Train Accuracy: 0.831
Train Accuracy: 0.832
Train Accuracy: 0.834
Train Accuracy: 0.832
Train Accuracy: 0.833
Train Accuracy: 0.834
Train Accuracy: 0.835
Train Accuracy: 0.835
Train Accuracy: 0.835
Train Accuracy: 0.837
Train Accuracy: 0.835
Train Accuracy: 0.836
Train Accuracy: 0.836
Train Accuracy: 0.837
Train Accuracy: 0.836
Train Accuracy: 0.839
Train Accuracy: 0.840
Train Accuracy: 0.840
Train Accuracy: 0.841
Train Accuracy: 0.839
Train Accuracy: 0.842
Train Accuracy: 0.841
Train Accuracy: 0.840
Train Accuracy: 0.842
Train Accuracy: 0.839
Train Accuracy: 0.845
Train Accuracy: 0.842
Train Accuracy: 0.843
Train Accuracy: 0.846
Train Accuracy: 0.846
Train Accuracy: 0.843
Train Accuracy: 0.845
Train Accuracy: 0.848
Train Accuracy: 0.847
Train Accuracy: 0.846
Train Accuracy: 0.848
Train Accuracy: 0.848
Train Accuracy: 0.849
Train Accuracy: 0.848
Train Accuracy: 0.850
Train Accuracy: 0.852
Train Accuracy: 0.848
Train Accuracy: 0.845
Train Accuracy: 0.851
Train Accuracy: 0.850
Train Accuracy: 0.853
Train Accuracy: 0.853
Train Accuracy: 0.850
Train Accuracy: 0.852
Train Accuracy: 0.854
Train Accuracy: 0.852
Train Accuracy: 0.852
Train Accuracy: 0.854
Train Accuracy: 0.855
Train Accuracy: 0.855
Train Accuracy: 0.857
Train Accuracy: 0.854
Train Accuracy: 0.857
Train Accuracy: 0.857
Train Accuracy: 0.855
Train Accuracy: 0.854
Train Accuracy: 0.858
Train Accuracy: 0.857
Train Accuracy: 0.859
Train Accuracy: 0.857
Train Accuracy: 0.859
Train Accuracy: 0.859
Train Accuracy: 0.859
Train Accuracy: 0.857
Train Accuracy: 0.860
Train Accuracy: 0.863
Train Accuracy: 0.863
Train Accuracy: 0.863
Train Accuracy: 0.862
Train Accuracy: 0.861
Train Accuracy: 0.865
Train Accuracy: 0.863
Train Accuracy: 0.864
Train Accuracy: 0.866
Train Accuracy: 0.864
Train Accuracy: 0.866
Train Accuracy: 0.866
Train Accuracy: 0.866
Train Accuracy: 0.865
Train Accuracy: 0.867
Train Accuracy: 0.870
Train Accuracy: 0.864
Train Accuracy: 0.869
Train Accuracy: 0.870
Train Accuracy: 0.867
Train Accuracy: 0.870
Train Accuracy: 0.873
Train Accuracy: 0.873
Train Accuracy: 0.869
Train Accuracy: 0.871
Train Accuracy: 0.873
Train Accuracy: 0.868
Train Accuracy: 0.875
Train Accuracy: 0.870
Train Accuracy: 0.873
Train Accuracy: 0.873
Train Accuracy: 0.872
Train Accuracy: 0.872
Train Accuracy: 0.876
Train Accuracy: 0.871
Train Accuracy: 0.875
Train Accuracy: 0.877
Train Accuracy: 0.875
Train Accuracy: 0.879
Train Accuracy: 0.876
Train Accuracy: 0.877
Train Accuracy: 0.877
Train Accuracy: 0.879
Train Accuracy: 0.880
Train Accuracy: 0.876
Train Accuracy: 0.876
Train Accuracy: 0.878
Train Accuracy: 0.879
Train Accuracy: 0.873
Train Accuracy: 0.877
Train Accuracy: 0.881
Train Accuracy: 0.881
Train Accuracy: 0.880
Train Accuracy: 0.880
Train Accuracy: 0.878
Train Accuracy: 0.880
Train Accuracy: 0.877
Train Accuracy: 0.882
Train Accuracy: 0.879
Train Accuracy: 0.881
Train Accuracy: 0.883
Train Accuracy: 0.884
Train Accuracy: 0.884
Train Accuracy: 0.881
Train Accuracy: 0.887
Train Accuracy: 0.882
Train Accuracy: 0.882
Train Accuracy: 0.881
Train Accuracy: 0.884
Train Accuracy: 0.884
Train Accuracy: 0.885
Train Accuracy: 0.888
Train Accuracy: 0.882
Train Accuracy: 0.889
Train Accuracy: 0.884
Train Accuracy: 0.885

:

:

:

:

:

:

:

:

:

: